### ISSUE TITLE
Please, sir, can I have some more?

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/homepage#3]
URL to the Paleontology Fund, which can be used for the purpose of donations to support Macrostrat:
http://www.supportuw.org/giving?seq=3141

Migrated from https://github.com/UW-Macrostrat/burwell/issues/15

**Comment by jczaplew** [comment]
Added in 6d72a1f6ee5ed4e6c50decfd42ab2dfe328a5dd2 and pushed to dev. Make any changes to the copy you wish.

**Comment by jczaplew** [comment]
Changes look good. Pulled to dev. Should be pull on production?

**Comment by cambro** [comment]
sure!

On Tue, Feb 16, 2016 at 8:22 AM, John J Czaplewski <notifications@github.com
